### ISSUE TITLE
API auth error in versions 0.2.2 and 0.2.3

### ISSUE THREAD

**Issue by tw3n** [cullenmcdermott/terraform-provider-porkbun#42]
I recently encountered a problem after updating from version 0.2.1 to 0.2.2 and 0.2.3. In these newer versions, I get an API auth error with the message `Error: status: 400 message: {"status":"ERROR","message":"Invalid API key. (001)"}`, even though the access and secret key remain unchanged. Unfortunately, I haven't yet had time to delve into the exact code behind this issue. Am I missing something obvious?

**Comment by cullenmcdermott** [comment]
Can you share your configuration including your provider configuration with any secrets redacted.

**Comment by cullenmcdermott** [comment]
Also which version did you start seeing this with, 0.2.2? and are still seeing it with 0.2.3?

**Comment by tw3n** [comment]
Sure! Here's a minimal reproducible example:

```tf
terraform {
  required_providers {
    porkbun = {
      source  = "cullenmcdermott/porkbun"
      version = "0.2.2"
    }
  }
}

provider "porkbun" {
  api_key    = var.porkbun.api_key
  secret_key = var.porkbun.secret_key
}

resource "porkbun_dns_record" "this" {
  name    = "test"
  domain  = "domain.com"
  content = "1.1.1.1"
  type    = "A"
}
```

Applying this configuration results in the following error:

```
│ Error: Error creating DNS Record
│ 
│   with porkbun_dns_record.this,
│   on main.tf line 15, in resource "porkbun_dns_record" "this":
│   15: resource "porkbun_dns_record" "this" {
│ 
│ Error: status: 400 message: {"status":"ERROR","message":"Invalid API key. (001)"}
```

This error occurs in version `0.2.2` and `0.2.3`. When I revert to version `0.2.1`, the configuration is applied without any issues.

**Comment by rico-cedar** [comment]
Had the same problem with 0.2.3.  

Remove:
```  
api_key    = var.porkbun.api_key 
secret_key = var.porkbun.secret_key
```

Just `provider "porkbun" {}`
Then locally I set an environmental variable to: PORKBUN_API_KEY and PORKBUN_SECRET_KEY.  

I was trying to get this also to work with Gitlab CI, so I also had to name the variables in Gitlab: TF_VAR_PORKBUN_API_KEY and TF_VAR_PORKBUN_SECRET_KEY.

Even after all that, I get a new error:
```
porkbun_dns_record.porkbun_dns_vault: Destroying... [id=0]
╷
│ Error: Error deleting record
│ 
│ Error: status: 400 message: {"status":"ERROR","message":"You need to pass an ID."}
```

Good to know I can revert though.

**Comment by cullenmcdermott** [comment]
Thanks for the info! This is definitely a regression. I'll work on this as soon as I can.

@rico-cedar that last error is because the id did not get saved into state for some reason, if you `terraform state rm` the resource then it should fix that error.

**Comment by tkellogg** [comment]
poking my head in here to confirm that I also had the same error and that setting environment variables fixes it
