### ISSUE TITLE
Error: Resource type not found on 0.2.4

### ISSUE THREAD

**Issue by tommyalatalo** [cullenmcdermott/terraform-provider-porkbun#53]
When running 0.2.4 I get the below errors. Has something broken with the last release?
I'm not seeing any changes to the documentation indicating that the resource names have changed.

If I revert to 0.2.3 then the resources are updated from the API, but then I get "Invalid API key" errors then the plan is created.

```
│ Error: Resource Type Not Found
│
│   with porkbun_dns_record.wildcard,
│   on dns.tf line 1, in resource "porkbun_dns_record" "wildcard":
│    1: resource "porkbun_dns_record" "wildcard" {
│
│ No resource type named "porkbun_dns_record" was found in the provider.
```

I'm configuring the provider like this:

```
    provider "porkbun" {
      api_key = data.vault_generic_secret.terraform.data["porkbun_api_key"]
      secret_key = data.vault_generic_secret.terraform.data["porkbun_secret_key"]
    }

    terraform {
      required_providers {
        porkbun = {
          source = "cullenmcdermott/porkbun"
          version = "0.2.4"
        }
      }
    }
```

**Comment by cullenmcdermott** [comment]
Hi! Nothing should have broken in the last release, I’ve been using it and my testing still passes. Can you please share an example of your resource configuration that is causing this as well?

**Comment by tommyalatalo** [comment]
They're all in this form, redacted domain for privacy:
```
resource "porkbun_dns_record" "example_com_alias" {
  domain  = "example.com"
  name    = ""
  type    = "ALIAS"
  content = "example.gitlab.io"
}
```

**Comment by cullenmcdermott** [comment]
So far I'm unable to replicate this. What I've tried so far is a configuration like this:
```
// Keys are set via environment variables
provider "porkbun" {}

terraform {
  required_providers {
    porkbun = {
      source = "cullenmcdermott/porkbun"
      version = "0.2.4"
    }
  }
}

variable "domain" {}

resource "porkbun_dns_record" "example_com_alias" {
  domain  = var.domain
  name    = ""
  type    = "ALIAS"
  content = "example.gitlab.io"
}
```
I also tried this from an existing as well as a fresh workspace and it all worked fine.

Could you try the following for me? Delete your `.terraform` directory and run a new `terraform init -upgrade`? Sometimes that can fix weird terraform issues.  If that doesn't help can you set `TF_LOG=trace` and send me the output of `terraform init -upgrade && terraform plan`?

**Comment by tommyalatalo** [comment]
I've tried removing the terraform cache several times, it doesn't help unfortunately.
I'm using Terraform 1.6.1 and Terragrunt on the latest version, not that Terragrunt really should affect this, it's just a wrapper. Here is the trace output from the init and plan: https://hastebin.com/share/fikacemazu.java

**Comment by cullenmcdermott** [comment]
Hi! I was able to replicate this by upgrading to TF 1.6.1. Thank you for mentioning that. I'll. dig into this more as soon as I can.

**Comment by tommyalatalo** [comment]
Any updates on this? Not that this is urgent but I'm in an unfortunate situation where I can't downgrade to make this work again, so I'm currently blocked from updating my DNS with Terraform :|

**Comment by JakeMittleman** [comment]
I would also love an update on this :)

**Comment by cullenmcdermott** [comment]
This is related to https://github.com/hashicorp/terraform-plugin-framework/issues/853

**Comment by tommyalatalo** [comment]
Thanks for fixing this!
